# Default values for tekton-pipeline.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


deployment:
  projects:
  - name: att-stage
  - name: att-prod

application_name: spring-rest-app
application_tag: latest
application_stage_namespace: att-stage
application_dev_namespace: att-demo

pipeline:
  image_stream_namespace: openshift
  namespace: att-demo
  image_stream_name: openjdk-8-rhel8:1.2
  source_repo: https://github.com/malacourse/spring-rest.git
  source_ref: master
  source_context_dir: basic-spring-boot
  webhook_secret_key: ATT_DEMO_KEY
  webhook_secret_val: foo-bar-123
  resource_name: spring-rest-1.0.0.jar

sonar:
  route: http://sonarqube-insecure-labs-cicd.apps.att-demo.ocp-labs.rhtelco.io/
  username: admin
  password: admin
  

