# Default values for namespace-manager.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


defaults:
  pods: "2"
  cpu_limit: "2"
  memory_limit: "8Gi"

projects:
  - namespace: mikel-dev
    owner: mikeldev
    pods: 4
