# Default values for namespace-manager.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


defaults:
  pods: "4"
  cpu_limit: "16"
  memory_limit: "8Gi"

projects:
  - namespace: user1-dev
    owner: user1
