# Default values for namespace-manager.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.


defaults:
  pods: "2"
  cpu_limit: "2"
  memory_limit: "8Gi"

projects:
  - namespace: mikel-dev
    pods: 6
    memory_limit: 16Gi
    cpu_limit: 4
    owner: mikeldev
