---
apiVersion: v1
kind: Secret
metadata:
  name: webhook-secret
  namespace: {{ .Values.pipeline.namespace }}
stringData:
  token: {{ .Values.pipeline.webhook_secret_key }}
  secret: {{ .Values.pipeline.webhook_secret_val }}
---
apiVersion: v1
kind: Secret
metadata:
  name: github-secret
  namespace: {{ .Values.pipeline.namespace }}
stringData:
  username: {{ .Values.pipeline.github_secret_username }}
  token: {{ .Values.pipeline.github_secret_token }}
